version: 2.1
jobs:
  test:
    docker:
      - image: busybox
    steps:
      - run:
          name: hello
          command: echo 'hello'
      - run:
          name: test
          command: |
            echo 'test'
  build:
    docker:
      - image: curlimages/curl
    steps:
      - run:
          name: action webhook
          command: |
            cat \<< EOF_A > /tmp/tmp-message.json
            {
              "event_type": "${CIRCLE_BRANCH}"
            }
            EOF_A
            JSON="$(cat /tmp/tmp-message.json)"
            curl -H "Authorization: token ${PAT}" -d "${JSON}" https://api.github.com/repos/rainchei/actions-webhook/dispatches

workflow-filter: &workflow-filter
  filters:
    branches:
      only:
        - main
        - dev
    tags:
      only:
        - /^ci.*/

workflows:
  test-and-build:
    jobs:
      - test:
          <<: *workflow-filter
      - build:
          <<: *workflow-filter
          context: actions-webhook
          requires:
            - test

