version: 2.1
jobs:
  build:
    docker:
      - image: gcr.io/google-containers/busybox:1.24
    steps:
      - run:
          name: hello
          command: echo 'hello'
      - run:
          name: echo
          command: echo $PAT

workflows:
  branch-build:
    jobs:
      - build:
          context: actions-webhook
          filters:
            branches:
              only:
                - main
