version: 2.1
jobs:
  test:
    docker:
      - image: busybox
    steps:
      - run:
          name: hello
          command: echo 'hello'
      - run:
          name: var
          command: |
            echo $foo
  build:
    docker:
      - image: curlimages/curl
    steps:
      - run:
          name: build
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ] \
            || [ "${CIRCLE_BRANCH}" == "dev" ]
            then
              echo "Build for image:"
              echo "- commit_sha: ${CIRCLE_SHA1}"
              echo "- branch: ${CIRCLE_BRANCH}"
              JSON='{ "event_type": "create", "client_payload": { "commit_sha": '\"${CIRCLE_SHA1}\"', "branch": '\"${CIRCLE_BRANCH}\"' } }'
              curl -H "Authorization: token ${PAT}" -d "${JSON}" https://api.github.com/repos/rainchei/actions-webhook/dispatches
            else
              echo "No need to build for ${CIRCLE_BRANCH}."
            fi


workflow-filter: &workflow-filter
  filters:
    branches:
      only:
        - main
        - dev
    tags:
      only:
        - /^ci.*/

workflows:
  test-and-build:
    jobs:
      - test:
          <<: *workflow-filter
      - build:
          <<: *workflow-filter
          context: actions-webhook
          requires:
            - test

