version: 2.1
jobs:
  test:
    docker:
      - image: busybox
    steps:
      - run:
          name: hello
          command: echo 'hello'
  build:
    docker:
      - image: bash
    steps:
      - run: |
          apk add curl
          case ${CIRCLE_BRANCH} in
            main)
              echo "Build for image:"
              echo "- commit_sha: ${CIRCLE_SHA1}"
              echo "- branch: ${CIRCLE_BRANCH}"
              echo
              cat \<< EOF_A > /tmp/tmp-message.json
              {
                "event_type": "create",
                "client_payload": {
                  "commit_sha": "${CIRCLE_SHA1}",
                  "branch": "${CIRCLE_BRANCH}"
                }
              }
              EOF_A
              JSON="$(cat /tmp/tmp-message.json)"
              curl -H "Authorization: token ${PAT}" -d "${JSON}" https://api.github.com/repos/rainchei/actions-webhook/dispatches
              ;;
            *)
              echo "No need to build for ${CIRCLE_BRANCH}."
              echo
              ;;
          esac

workflow-filter: &workflow-filter
  filters:
    branches:
      only:
        - main
        - dev
    tags:
      only:
        - /^ci.*/

workflows:
  test-and-build:
    jobs:
      - test:
          <<: *workflow-filter
      - build:
          <<: *workflow-filter
          context: actions-webhook
          requires:
            - test

