version: 2.1
jobs:
  build:
    docker:
      - image: curlimages/curl
    steps:
      - run:
          name: hello
          command: echo 'hello'
      - run:
          name: echo
          command: >
            curl -H "Authorization: token ${PAT}" \
              --request POST \
              --data '{"event_type": "${CIRCLE_BRANCH}"}' \
              https://api.github.com/repos/rainchei/actions-webhook/dispatches

workflows:
  branch-build:
    jobs:
      - build:
          context: actions-webhook
          filters:
            branches:
              only:
                - main
