version: 2.1
jobs:
  build:
    steps:
      - run:
          name: hello
          command: echo 'hello'

workflows:
  branch-build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
