version: 2.1
jobs:
  test:
    docker:
      - image: busybox
    steps:
      - run:
          name: hello
          command: echo 'hello'
  build:
    docker:
      - image: curlimages/curl
    steps:
      - run:
          name: build
          command: |
            case "${CIRCLE_BRANCH}" in
              main)
                echo "Build for image:"
                echo "- commit_sha: ${CIRCLE_SHA1}"
                echo "- branch: ${CIRCLE_BRANCH}"
                ;;
              *)
                echo "No need to build for ${CIRCLE_BRANCH}."
                ;;
            esac

workflow-filter: &workflow-filter
  filters:
    branches:
      only:
        - main
        - dev
    tags:
      only:
        - /^ci.*/

workflows:
  test-and-build:
    jobs:
      - test:
          <<: *workflow-filter
      - build:
          <<: *workflow-filter
          context: actions-webhook
          requires:
            - test

