name: webhook-trigger

on:
  repository_dispatch:
    types:
      - create

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}
      - name: Hello
        run: |
          echo "Hello, I've been triggered by a webhook!"
      - name: Echo github.event
        run: |
          echo "Dispatch type: ${{ github.event.action }}"
          echo "commit sha: ${{ github.event.client_payload.commit_sha }}"
      - name: Goodbye
        if: ${{ contains(github.event.client_payload.branch, 'main') }}
        run: npx cowsay "Bye!"
      - name: Adios
        if: ${{ contains(github.event.client_payload.branch, 'dev') }}
        run: npx cowsay "Adios!"
