name: webhook-trigger

on:
  repository_dispatch:
    types:
      - main
      - dev

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.action }}
      - name: Hello
        run: echo "Hello, I've been triggered by a webhook!"
      - name: Event Name
        run: |
          echo "Event triggered by ${GITHUB_EVENT_NAME}"
          echo "Dispatch type ${{ github.event.action }}"
          cat this_branch
      - name: Goodbye
        if: ${{ github.event.action == 'main' }}
        run: npx cowsay "Bye!"
      - name: Adios
        if: ${{ github.event.action == 'dev' }}
        run: npx cowsay "Adios!"
