name: webhook-trigger

on:
  repository_dispatch:
    types:
      - webhook-one
      - webhook-two

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-vesion: '12'
      - name: Hello
        run: echo "Hello, I've been triggered by a webhook!"
      - name: Even Name
        run: |
          echo "Even triggered by ${GITHUB_EVENT_NAME}"
          echo "Dispatch type ${{ github.event.action }}"
      - name: Goodbye
        if: ${{ github.event.action == "webhook-one" }}
        run: npx cowsay "Bye!"
      - name: Adios
        if: ${{ github.event.action == "webhook-two" }}
        run: npx cowsay "Adios!"
